# Generated by Django 2.2.10 on 2020-02-18 15:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_key', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Unique key')),
                ('hidden', models.BooleanField(default=False, verbose_name='Is hidden')),
                ('image', models.ImageField(height_field='height', upload_to='i/%Y/%m/', verbose_name='Image file', width_field='width')),
                ('thumb_small', models.ImageField(blank=True, upload_to='i/%Y/%m/', verbose_name='Small thumbnail')),
                ('thumb_large', models.ImageField(blank=True, upload_to='i/%Y/%m/', verbose_name='Large thumbnail')),
                ('extension', models.CharField(blank=True, default='', max_length=5, verbose_name='Extension')),
                ('height', models.PositiveIntegerField(blank=True, default=0, verbose_name='Height')),
                ('width', models.PositiveIntegerField(blank=True, default=0, verbose_name='Width')),
                ('source', models.URLField(blank=True, max_length=2048, null=True, verbose_name='Source')),
                ('is_meme', models.BooleanField(default=False, verbose_name='Is meme')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created on')),
                ('source_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_memes', to='images.Image', verbose_name='Source image')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ('-created_on',),
            },
        ),
    ]
