project_domain: i.miximum.fr
web_domain: "{{ project_domain }}"
project_version: master
certbot_admin_email: certbot@thibault.miximum.fr
certbot_domains: "{{ project_domain }},{{ web_domain }}"
cert_path: "/etc/letsencrypt/live/{{ project_domain }}"
django_settings: core.settings.production
project_env: production
env_file: .env.production
env_target: .env.production
gunicorn_options: ""
shell_prompt: PS1='${debian_chroot:+($debian_chroot)}\[\033[01;31m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
